// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FriendController from "./friend_controller"
application.register("friend", FriendController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import SearchPlantController from "./search_plant_controller"
application.register("search-plant", SearchPlantController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)
