meta_name: "Plantaqua"
meta_title: "Plantaqua - Know when your plants need you!"
meta_description: "Plantaqua is the best plant app to help you take care of them. Get custom notifications when your plants need you!"
meta_image: "plantaqua.png"
# twitter_account: "@plantaqua"
