meta_name: "Plantaqua"
meta_title: "Plantaqua - Know when your plants need you."
meta_description: "The grass is greener where you water it!"
meta_image: "plantaqua.png"
# twitter_account: "@plantaqua"
